### ISSUE TITLE
html-node

### ISSUE THREAD

**Issue by fraschm1998** [YoloDev/rstml-component#14]
How does this compare to: https://github.com/vidhanio/html-node

**Comment by Alxandr** [comment]
As far as I understood, `html-node` produces a "vdom" of nodes (one for each HTML node in the rendered template). I explicitly did not want that (as you will have to allocate all of the nodes, and all of the children etc.)

You can think of `rstml-component` a bit more like `serde` but for serializing to HTML. It provides traits, macros and utilities for describing how a struct get's serialized into HTML (or HTML attributes). This means you can't inspect the output as a DOM, you just get out a string or a byte array of utf-8 encoded HTML, but it also means that you don't have to first walk your structs and turn them into a DOM, then walk the DOM to turn that into a string.

**Comment by fraschm1998** [comment]
So would html-node be more similar to [go templ](https://github.com/a-h/templ)? And how does rstml-component differ from other rust templating engines? Do you still need to use askama or maud?

**Comment by Alxandr** [comment]
You don't "need to" use anything? I don't even know what askama or maud is. Go templ probably isn't too terribly far off, except you need to use macros, and the switching back and forth between "html" and rust is probably a bit more painfull.

**Comment by fraschm1998** [comment]
> I don't even know what askama or maud is.

[Askama](https://github.com/djc/askama) is a rust templating engine like pythons jinja. And [Maud](https://github.com/lambda-fairy/maud) is another templating engine a bit more similar to go's templ but uses classes instead of regular html for the elements.

**Comment by fraschm1998** [comment]
Issue with maud right now, with their custom syntax, it doesn't fully support alpinejs, htmx and doesn't integrate well with tailwindcss
